# Generated by Django 4.2.2 on 2023-07-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DLL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=248)),
                ('sha256', models.CharField(max_length=64)),
                ('signing_date', models.DateTimeField()),
                ('version', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('virtual_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WindowsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WindowsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('release_version', models.CharField(max_length=100)),
                ('windows_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.windowsversion')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=100)),
                ('function_c', models.TextField()),
                ('function_c_hash', models.CharField(max_length=70)),
                ('dll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dll')),
            ],
        ),
        migrations.AddField(
            model_name='dll',
            name='windows_updates',
            field=models.ManyToManyField(to='backend.windowsupdate'),
        ),
    ]
