# Generated by Django 4.2.2 on 2023-07-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dll',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dll',
            name='sha256',
        ),
        migrations.RemoveField(
            model_name='dll',
            name='signing_date',
        ),
        migrations.RemoveField(
            model_name='dll',
            name='size',
        ),
        migrations.RemoveField(
            model_name='dll',
            name='version',
        ),
        migrations.RemoveField(
            model_name='dll',
            name='virtual_size',
        ),
        migrations.RemoveField(
            model_name='dll',
            name='windows_updates',
        ),
        migrations.CreateModel(
            name='DLLInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=248)),
                ('sha256', models.CharField(max_length=64)),
                ('signing_date', models.DateTimeField()),
                ('version', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('virtual_size', models.IntegerField()),
                ('dll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dll')),
                ('windows_updates', models.ManyToManyField(to='backend.windowsupdate')),
            ],
        ),
    ]
