# Generated by Django 4.2.2 on 2023-07-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_dll_description_remove_dll_sha256_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dllinstance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dllinstance',
            name='name',
        ),
        migrations.AddField(
            model_name='dll',
            name='description',
            field=models.CharField(default='', max_length=248),
            preserve_default=False,
        ),
    ]
