# Generated by Django 4.2.2 on 2023-07-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_dllinstance_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='dll',
        ),
        migrations.AddField(
            model_name='function',
            name='dll_instance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.dllinstance'),
            preserve_default=False,
        ),
    ]
