# Generated by Django 4.2.2 on 2024-02-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_function_dll_function_dll_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=2048)),
                ('post_patch_dll_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_patch_patches', to='backend.dllinstance')),
                ('pre_patch_dll_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_patch_patches', to='backend.dllinstance')),
            ],
        ),
        migrations.CreateModel(
            name='PatchFunctionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.function')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_functions', to='backend.patch')),
            ],
        ),
    ]
